package nanolive.psxj.emu.devices;

import nanolive.psxj.emu.sio.ControllerDevice;
import nanolive.psxj.emu.sio.ControllerDeviceFactory;
import nanolive.psxj.emu.sio.ControllerDeviceState;
import nanolive.psxj.emu.sio.DigitalController;
import nanolive.psxj.emu.sio.MemoryCard;
import nanolive.psxj.emu.sio.MultitapController;
import nanolive.psxj.util.Log;

import java.io.IOException;
import java.nio.file.Path;
import java.util.ArrayDeque;
import java.util.Iterator;
import java.util.function.IntConsumer;

/**
 * PlayStation SIO0 (controller/memory-card serial port).
 *
 * <p>The serial shift register and the peripheral /ACK signal are deliberately
 * modelled separately.  On real hardware the byte has finished shifting before
 * the peripheral pulls /ACK low; IRQ7 is generated by that later edge, not by
 * completion of the serial byte itself.</p>
 */
public final class SioController {

    private static final int STATUS_TX_READY = 0x0001;
    private static final int STATUS_RX_NOT_EMPTY = 0x0002;
    private static final int STATUS_TX_IDLE = 0x0004;
    private static final int STATUS_ACK_LEVEL = 0x0080;
    private static final int STATUS_IRQ = 0x0200;

    private static final int CTRL_TX_ENABLE = 0x0001;
    private static final int CTRL_DTR = 0x0002;
    private static final int CTRL_RX_ENABLE = 0x0004;
    private static final int CTRL_ACKNOWLEDGE = 0x0010;
    private static final int CTRL_RESET = 0x0040;
    private static final int CTRL_TX_IRQ_ENABLE = 0x0400;
    private static final int CTRL_RX_IRQ_ENABLE = 0x0800;
    private static final int CTRL_DSR_IRQ_ENABLE = 0x1000;
    private static final int CTRL_PORT_SELECT = 0x2000;
    private static final int CTRL_READABLE_MASK = 0x3F0F;

    private static final int RX_FIFO_CAPACITY = 8;
    private static final int ACK_LOW_CYCLES = 100;
    private static final int NORMAL_ACK_FROM_TRANSFER_START_CYCLES = 1_500;
    private static final int SONY_CARD_READ_DELAY_CYCLES = 31_000;

    private static final int CARD_COMMAND_READ = 0x52;
    private static final int CARD_COMMAND_WRITE = 0x57;
    private static final int CARD_COMMAND_ID = 0x53;
    private static final int CARD_SECTOR_SIZE = 128;
    private static final int CARD_SECTOR_COUNT = MemoryCard.SIZE / CARD_SECTOR_SIZE;

    public static final int PAD_SELECT = 0x0001;
    public static final int PAD_L3 = 0x0002;
    public static final int PAD_R3 = 0x0004;
    public static final int PAD_START = 0x0008;
    public static final int PAD_UP = 0x0010;
    public static final int PAD_RIGHT = 0x0020;
    public static final int PAD_DOWN = 0x0040;
    public static final int PAD_LEFT = 0x0080;
    public static final int PAD_L2 = 0x0100;
    public static final int PAD_R2 = 0x0200;
    public static final int PAD_L1 = 0x0400;
    public static final int PAD_R1 = 0x0800;
    public static final int PAD_TRIANGLE = 0x1000;
    public static final int PAD_CIRCLE = 0x2000;
    public static final int PAD_CROSS = 0x4000;
    public static final int PAD_SQUARE = 0x8000;

    private enum DeviceType { NONE, CONTROLLER, MEMCARD }

    private final InterruptController interruptController;
    private final ArrayDeque<Integer> rxFifo = new ArrayDeque<>(RX_FIFO_CAPACITY);
    private final ControllerDevice[] controllers = {
        new DigitalController(),
        new DigitalController()
    };
    private final DigitalController.RumbleHandler[] rumbleHandlers = new DigitalController.RumbleHandler[2];
    private volatile IntConsumer memoryCardWriteListener;

    private MemoryCard slot1;
    private MemoryCard slot2;
    private boolean controller1Connected = true;
    private boolean controller2Connected;
    private DeviceType currentDevice = DeviceType.NONE;
    private int activeControllerPort = -1;

    private int mode;
    private int control;
    private int baudrate;
    private int baudrateTimer;
    private int baudrateReload;
    private int selectedPort;

    private int commandStep;
    private int memcardCommand;
    private int memcardAddress;
    private int memcardChecksum;
    private int memcardPreviousByte;
    private boolean memcardAddressValid;
    private boolean memcardChecksumValid;
    private final byte[] memcardWriteBuffer = new byte[CARD_SECTOR_SIZE];

    public void setMemoryCardWriteListener(IntConsumer listener) {
        memoryCardWriteListener = listener;
    }

    // Byte in the active shift register, or a byte waiting for TXEN.
    private int queuedTxData = -1;
    // One-byte TX holding register.
    private int holdingTxData = -1;
    private boolean queuedTxEnableLatched;
    private boolean holdingTxEnableLatched;
    private int serialCyclesRemaining;

    private int ackDelayRemaining;
    private int ackCyclesRemaining;
    private boolean ackPulseActive;
    private boolean irqPending;
    private int lastRxByte;
    private int emptyRxReads;
    private BeamPositionSource beamPositionSource;
    private boolean lightgunIrqLineActive;
    private boolean lightgunSamplingPossible;

    public SioController(InterruptController interruptController) {
        this.interruptController = interruptController;
    }

    /** Supplies the exact physical GPU beam position used by IRQ10 lightguns. */
    @FunctionalInterface
    public interface BeamPositionSource {
        ControllerDevice.BeamPosition position();
    }

    public void setBeamPositionSource(BeamPositionSource source) {
        beamPositionSource = source;
        refreshLightgunSampling();
        if (source == null && lightgunIrqLineActive) {
            lightgunIrqLineActive = false;
            interruptController.clear(10);
        }
    }

    public void attachMemoryCards(Path slot1Path, Path slot2Path) throws IOException {
        flush();
        MemoryCard nextSlot1 = slot1Path == null ? null : MemoryCard.openOrCreate(slot1Path);
        MemoryCard nextSlot2 = slot2Path == null ? null : MemoryCard.openOrCreate(slot2Path);
        slot1 = nextSlot1;
        slot2 = nextSlot2;
        if (slot1 != null) {
            Log.info("Attached memory card slot1: " + slot1Path);
        }
        if (slot2 != null) {
            Log.info("Attached memory card slot2: " + slot2Path);
        }
    }

    public void setButtonState(int mask, boolean pressed) {
        setButtonState(0, mask, pressed);
    }

    public void setButtonState(int port, int mask, boolean pressed) {
        DigitalController controller = digitalController(port);
        if (controller != null) {
            controller.setButtonState(mask, pressed);
        }
    }

    public void setControllerState(int pressedMask, int leftX, int leftY, int rightX, int rightY) {
        setControllerState(0, pressedMask, leftX, leftY, rightX, rightY);
    }

    public void setControllerState(
        int port,
        int pressedMask,
        int leftX,
        int leftY,
        int rightX,
        int rightY
    ) {
        DigitalController controller = digitalController(port);
        if (controller != null) {
            controller.setControllerState(pressedMask, leftX, leftY, rightX, rightY);
        }
    }

    public void setRumbleHandler(DigitalController.RumbleHandler handler) {
        setRumbleHandler(0, handler);
    }

    public void setRumbleHandler(int port, DigitalController.RumbleHandler handler) {
        validatePort(port);
        rumbleHandlers[port] = handler;
        installRumbleHandler(port);
    }

    public void setControllerDevice(int port, ControllerDevice device) {
        validatePort(port);
        if (currentDevice == DeviceType.CONTROLLER && activeControllerPort == port) {
            resetSession();
        }
        controllers[port] = device;
        if (port == 0) {
            controller1Connected = device != null;
        } else {
            controller2Connected = device != null;
        }
        installRumbleHandler(port);
        refreshLightgunSampling();
    }

    public ControllerDevice controllerDevice(int port) {
        validatePort(port);
        return controllers[port];
    }

    public MultitapController attachMultitap(int port) {
        MultitapController multitap = new MultitapController();
        setControllerDevice(port, multitap);
        return multitap;
    }

    public void setMultitapController(int port, int slot, ControllerDevice device) {
        validatePort(port);
        ControllerDevice portDevice = controllers[port];
        if (!(portDevice instanceof MultitapController multitap)) {
            throw new IllegalStateException("Physical port " + port + " has no multitap");
        }
        if (currentDevice == DeviceType.CONTROLLER && activeControllerPort == port) {
            resetSession();
        }
        multitap.setController(slot, device);
        installRumbleHandler(port);
        refreshLightgunSampling();
    }

    public void setControllerConnected(int port, boolean connected) {
        validatePort(port);
        if (!connected && currentDevice == DeviceType.CONTROLLER
            && activeControllerPort == port) {
            resetSession();
        }
        if (connected && controllers[port] == null) {
            controllers[port] = new DigitalController();
            installRumbleHandler(port);
        }
        if (port == 0) {
            controller1Connected = connected;
        } else {
            controller2Connected = connected;
        }
        refreshLightgunSampling();
    }

    public boolean controllerConnected(int port) {
        validatePort(port);
        return port == 0 ? controller1Connected : controller2Connected;
    }

    public int read8(int address) {
        int offset = address & 0x0F;
        if (offset <= 3) {
            if (offset == 0) {
                return popRxByte();
            }
            return peekRxByte(offset);
        }
        int register;
        int shift;
        if (offset >= 4 && offset <= 7) {
            register = status();
            shift = (offset - 4) * 8;
        } else if (offset >= 8 && offset <= 9) {
            register = mode;
            shift = (offset - 8) * 8;
        } else if (offset >= 0xA && offset <= 0xB) {
            register = control;
            shift = (offset - 0xA) * 8;
        } else if (offset >= 0xE) {
            register = baudrate;
            shift = (offset - 0xE) * 8;
        } else {
            return 0xFF;
        }
        return (register >>> shift) & 0xFF;
    }

    public int read16(int address) {
        return switch (address & 0x0F) {
            case 0x0 -> {
                int low = peekRxByte(0);
                int high = peekRxByte(1);
                popRxByte();
                yield low | (high << 8);
            }
            case 0x2 -> peekRxByte(1) | (peekRxByte(2) << 8);
            case 0x4 -> status() & 0xFFFF;
            case 0x6 -> (status() >>> 16) & 0xFFFF;
            case 0x8 -> mode & 0xFFFF;
            case 0xA -> control & 0xFFFF;
            case 0xE -> baudrate & 0xFFFF;
            default -> 0xFFFF;
        };
    }

    public int read32(int address) {
        return switch (address & 0x0F) {
            case 0x0 -> {
                int value = peekRxByte(0)
                    | (peekRxByte(1) << 8)
                    | (peekRxByte(2) << 16)
                    | (peekRxByte(3) << 24);
                int removed = 0;
                while (removed < 4 && !rxFifo.isEmpty()) {
                    lastRxByte = rxFifo.removeFirst() & 0xFF;
                    removed++;
                }
                emptyRxReads = removed < 4 ? Math.min(3, 4 - removed) : 0;
                evaluateLevelInterrupts();
                yield value;
            }
            case 0x4 -> status();
            case 0x8 -> (mode & 0xFFFF) | ((control & 0xFFFF) << 16);
            case 0xC -> 0xFFFF | ((baudrate & 0xFFFF) << 16);
            default -> 0xFFFF_FFFF;
        };
    }

    public void write8(int address, int value) {
        value &= 0xFF;
        switch (address & 0x0F) {
            case 0x0 -> startTransfer(value);
            case 0x8 -> mode = (mode & 0xFF00) | value;
            case 0x9 -> mode = (mode & 0x00FF) | (value << 8);
            case 0xA -> writeControl((control & 0xFF00) | value);
            case 0xB -> writeControl((control & 0x00FF) | (value << 8));
            case 0xE -> {
                baudrate = (baudrate & 0xFF00) | value;
                reloadBaudrateTimer();
            }
            case 0xF -> {
                baudrate = (baudrate & 0x00FF) | (value << 8);
                reloadBaudrateTimer();
            }
            default -> {
            }
        }
    }

    public void write16(int address, int value) {
        value &= 0xFFFF;
        switch (address & 0x0F) {
            case 0x0 -> startTransfer(value & 0xFF);
            case 0x8 -> mode = value;
            case 0xA -> writeControl(value);
            case 0xE -> {
                baudrate = value;
                reloadBaudrateTimer();
            }
            default -> {
            }
        }
    }

    private void writeControl(int value) {
        boolean oldDtr = (control & CTRL_DTR) != 0;
        int oldSelectedPort = selectedPort;
        if ((value & CTRL_RESET) != 0) {
            hardReset();
            return;
        }

        boolean acknowledge = (value & CTRL_ACKNOWLEDGE) != 0;
        control = value & CTRL_READABLE_MASK & ~(CTRL_ACKNOWLEDGE | CTRL_RESET);
        selectedPort = (control & CTRL_PORT_SELECT) != 0 ? 1 : 0;

        boolean newDtr = (control & CTRL_DTR) != 0;
        if (oldDtr && (!newDtr || oldSelectedPort != selectedPort)) {
            resetSession();
        }
        if (acknowledge) {
            clearIrq();
        }
        startWaitingTransferIfEnabled();
        evaluateLevelInterrupts();
    }

    public void tick(int cycles) {
        if (cycles <= 0) {
            return;
        }
        if (!lightgunSamplingPossible
            && baudrateReload == 0
            && serialCyclesRemaining <= 0
            && ackDelayRemaining <= 0
            && (!ackPulseActive || ackCyclesRemaining <= 0)) {
            return;
        }
        sampleLightgunIrqLine();
        advanceBaudrateTimer(cycles);
        if (serialCyclesRemaining <= 0
            && ackDelayRemaining <= 0
            && (!ackPulseActive || ackCyclesRemaining <= 0)) {
            return;
        }
        while (cycles > 0) {
            // Only advance timers which existed at the beginning of this slice.
            boolean serialWasActive = serialCyclesRemaining > 0;
            boolean ackDelayWasActive = ackDelayRemaining > 0;
            boolean ackPulseWasActive = ackPulseActive && ackCyclesRemaining > 0;
            int step = cycles;
            boolean timedState = false;
            if (serialWasActive) {
                step = Math.min(step, serialCyclesRemaining);
                timedState = true;
            }
            if (ackDelayWasActive) {
                step = Math.min(step, ackDelayRemaining);
                timedState = true;
            }
            if (ackPulseWasActive) {
                step = Math.min(step, ackCyclesRemaining);
                timedState = true;
            }
            if (!timedState || step <= 0) {
                break;
            }

            cycles -= step;
            if (serialWasActive) {
                serialCyclesRemaining -= step;
                if (serialCyclesRemaining == 0 && queuedTxData >= 0) {
                    completeTransfer();
                }
            }
            if (ackDelayWasActive) {
                ackDelayRemaining -= step;
                if (ackDelayRemaining == 0) {
                    beginAckPulse();
                }
            }
            if (ackPulseWasActive) {
                ackCyclesRemaining -= step;
                if (ackCyclesRemaining == 0) {
                    ackPulseActive = false;
                    evaluateLevelInterrupts();
                }
            }
        }
    }

    private void sampleLightgunIrqLine() {
        if (!lightgunSamplingPossible) {
            return;
        }
        boolean controller1Samples = controller1Connected
            && controllers[0] != null
            && controllers[0].samplesLightgunIrqLine();
        boolean controller2Samples = controller2Connected
            && controllers[1] != null
            && controllers[1].samplesLightgunIrqLine();
        if (!controller1Samples && !controller2Samples) {
            if (lightgunIrqLineActive) {
                interruptController.clear(10);
                lightgunIrqLineActive = false;
            }
            return;
        }
        ControllerDevice.BeamPosition position = beamPositionSource == null
            ? null
            : beamPositionSource.position();
        boolean asserted = false;
        if (position != null) {
            if (controller1Samples) {
                asserted |= controllers[0].lightgunIrqLine(position);
            }
            if (controller2Samples) {
                asserted |= controllers[1].lightgunIrqLine(position);
            }
        }
        if (asserted) {
            interruptController.raise(10);
        } else if (lightgunIrqLineActive) {
            interruptController.clear(10);
        }
        lightgunIrqLineActive = asserted;
    }

    public boolean gpuTimingIndependent() {
        return !lightgunSamplingPossible;
    }

    // Check for IRQ edges before batching clocks.
    public boolean interruptStableFor(int cycles) {
        if (cycles <= 0 || irqPending) {
            return true;
        }
        int irqControls = CTRL_TX_IRQ_ENABLE | CTRL_RX_IRQ_ENABLE | CTRL_DSR_IRQ_ENABLE;
        if ((control & irqControls) == 0) {
            return true;
        }
        return serialCyclesRemaining <= 0
            && ackDelayRemaining <= 0
            && (!ackPulseActive || ackCyclesRemaining <= 0);
    }

    private void refreshLightgunSampling() {
        lightgunSamplingPossible = beamPositionSource != null
            && ((controller1Connected && controllers[0] != null
                    && controllers[0].samplesLightgunIrqLine())
                || (controller2Connected && controllers[1] != null
                    && controllers[1].samplesLightgunIrqLine()));
    }

    public void flush() throws IOException {
        if (slot1 != null) {
            slot1.flush();
        }
        if (slot2 != null) {
            slot2.flush();
        }
    }

    public byte[] copyMemoryCard(int slot) {
        MemoryCard card = slot == 0 ? slot1 : slot2;
        return card == null ? new byte[0] : card.copyData();
    }

    public void loadMemoryCard(int slot, byte[] snapshot) {
        MemoryCard card = slot == 0 ? slot1 : slot2;
        if (card != null) {
            card.load(snapshot);
        }
    }

    public int status() {
        int status = 0;
        if (txFifoReady()) {
            status |= STATUS_TX_READY;
        }
        if (serialCyclesRemaining == 0 && queuedTxData < 0 && holdingTxData < 0) {
            status |= STATUS_TX_IDLE;
        }
        if (!rxFifo.isEmpty()) {
            status |= STATUS_RX_NOT_EMPTY;
        }
        if (ackPulseActive) {
            status |= STATUS_ACK_LEVEL;
        }
        if (irqPending) {
            status |= STATUS_IRQ;
        }
        return status | ((baudrateTimer & 0x1F_FFFF) << 11);
    }

    private boolean txFifoReady() {
        if (serialCyclesRemaining > 0) {
            return holdingTxData < 0;
        }
        return queuedTxData < 0;
    }

    private void startTransfer(int value) {
        boolean txEnabled = (control & CTRL_TX_ENABLE) != 0;
        if (serialCyclesRemaining > 0) {
            holdingTxData = value & 0xFF;
            holdingTxEnableLatched = txEnabled;
            return;
        }

        queuedTxData = value & 0xFF;
        queuedTxEnableLatched = txEnabled;
        startWaitingTransferIfEnabled();
    }

    private void startWaitingTransferIfEnabled() {
        if (serialCyclesRemaining != 0 || queuedTxData < 0) {
            return;
        }
        if ((control & CTRL_TX_ENABLE) == 0 && !queuedTxEnableLatched) {
            return;
        }
        serialCyclesRemaining = transferCyclesPerByte();
    }

    private void completeTransfer() {
        int txByte = queuedTxData & 0xFF;
        queuedTxData = -1;
        queuedTxEnableLatched = false;

        TransferResult result = exchangeByte(txByte);
        boolean csAsserted = (control & CTRL_DTR) != 0;
        boolean forcedReceive = (control & CTRL_RX_ENABLE) != 0;
        if (csAsserted || forcedReceive) {
            pushRxByte(result.response());
        }
        if (forcedReceive) {
            control &= ~CTRL_RX_ENABLE;
        }
        if (result.acknowledge()) {
            scheduleAck(result.extraAckDelay());
        }

        if (holdingTxData >= 0) {
            queuedTxData = holdingTxData;
            queuedTxEnableLatched = holdingTxEnableLatched;
            holdingTxData = -1;
            holdingTxEnableLatched = false;
            startWaitingTransferIfEnabled();
        }
        evaluateLevelInterrupts();
    }

    private TransferResult exchangeByte(int value) {
        if ((control & CTRL_DTR) == 0) {
            resetSession();
            return TransferResult.LAST_FF;
        }
        if (commandStep == 0) {
            return beginDeviceSelection(value);
        }
        return switch (currentDevice) {
            case CONTROLLER -> handleControllerByte(value);
            case MEMCARD -> handleMemcardByte(value);
            case NONE -> TransferResult.LAST_FF;
        };
    }

    private TransferResult beginDeviceSelection(int value) {
        ControllerDevice selectedController = selectedController();
        if (selectedController != null && selectedController.beginTransaction(value)) {
            currentDevice = DeviceType.CONTROLLER;
            activeControllerPort = selectedPort;
            commandStep = 1;
            return TransferResult.more(0xFF);
        }
        MemoryCard card = selectedMemoryCard();
        if (value == 0x81 && card != null) {
            currentDevice = DeviceType.MEMCARD;
            commandStep = 1;
            return TransferResult.more(0xFF);
        }
        resetSession();
        return TransferResult.LAST_FF;
    }

    private TransferResult handleControllerByte(int value) {
        ControllerDevice activeController = activeController();
        if (activeController == null) {
            resetSession();
            return TransferResult.LAST_FF;
        }
        ControllerDevice.CommandResult result;
        if (commandStep == 1) {
            result = activeController.beginCommand(value);
        } else {
            result = activeController.exchangeCommandByte(value);
        }
        if (result.finished()) {
            resetSession();
            return TransferResult.last(result.response());
        }
        commandStep++;
        return result.acknowledge()
            ? TransferResult.more(result.response())
            : TransferResult.last(result.response());
    }

    private TransferResult handleMemcardByte(int value) {
        MemoryCard card = selectedMemoryCard();
        if (card == null) {
            resetSession();
            return TransferResult.LAST_FF;
        }
        value &= 0xFF;

        if (commandStep == 1) {
            int flag = card.flag();
            if (value != CARD_COMMAND_READ && value != CARD_COMMAND_WRITE && value != CARD_COMMAND_ID) {
                resetSession();
                return TransferResult.last(flag);
            }
            memcardCommand = value;
            if (value == CARD_COMMAND_WRITE) {
                card.clearDirectoryUnreadFlag();
            }
            commandStep = 2;
            return TransferResult.more(flag);
        }
        if (commandStep == 2) {
            commandStep = 3;
            return TransferResult.more(0x5A);
        }
        if (commandStep == 3) {
            commandStep = 4;
            return TransferResult.more(0x5D);
        }
        if (memcardCommand == CARD_COMMAND_ID) {
            return handleMemcardId();
        }
        return handleMemcardReadWrite(card, value);
    }

    private TransferResult handleMemcardId() {
        return switch (commandStep++) {
            case 4 -> TransferResult.more(0x5C);
            case 5 -> TransferResult.more(0x5D);
            case 6 -> TransferResult.more(0x04);
            case 7, 8 -> TransferResult.more(0x00);
            case 9 -> {
                resetSession();
                yield TransferResult.last(0x80);
            }
            default -> {
                resetSession();
                yield TransferResult.LAST_FF;
            }
        };
    }

    private TransferResult handleMemcardReadWrite(MemoryCard card, int value) {
        if (commandStep == 4) {
            memcardAddress = value << 8;
            memcardChecksum = value;
            memcardPreviousByte = value;
            commandStep = 5;
            return TransferResult.more(0x00);
        }
        if (commandStep == 5) {
            int previous = memcardPreviousByte;
            memcardAddress |= value;
            memcardChecksum ^= value;
            memcardPreviousByte = value;
            memcardAddressValid = memcardAddress < CARD_SECTOR_COUNT;
            commandStep = 6;
            return TransferResult.more(previous);
        }
        if (memcardCommand == CARD_COMMAND_READ) {
            return handleMemcardRead(card);
        }
        return handleMemcardWrite(card, value);
    }

    private TransferResult handleMemcardRead(MemoryCard card) {
        if (commandStep == 6) {
            commandStep = 7;
            return TransferResult.moreDelayed(0x5C, SONY_CARD_READ_DELAY_CYCLES);
        }
        if (commandStep == 7) {
            commandStep = 8;
            return TransferResult.more(0x5D);
        }
        if (commandStep == 8) {
            commandStep = 9;
            return TransferResult.more(memcardAddressValid ? (memcardAddress >>> 8) : 0xFF);
        }
        if (commandStep == 9) {
            int response = memcardAddressValid ? memcardAddress : 0xFF;
            if (!memcardAddressValid) {
                resetSession();
                return TransferResult.last(response);
            }
            commandStep = 10;
            return TransferResult.more(response);
        }

        int payloadIndex = commandStep - 10;
        if (payloadIndex < CARD_SECTOR_SIZE) {
            int data = card.readByte(memcardAddress * CARD_SECTOR_SIZE + payloadIndex);
            memcardChecksum ^= data;
            commandStep++;
            return TransferResult.more(data);
        }
        if (payloadIndex == CARD_SECTOR_SIZE) {
            commandStep++;
            return TransferResult.more(memcardChecksum);
        }

        resetSession();
        return TransferResult.last(0x47);
    }

    private TransferResult handleMemcardWrite(MemoryCard card, int value) {
        int payloadIndex = commandStep - 6;
        if (payloadIndex < CARD_SECTOR_SIZE) {
            int response = memcardPreviousByte;
            memcardWriteBuffer[payloadIndex] = (byte) value;
            memcardChecksum ^= value;
            memcardPreviousByte = value;
            commandStep++;
            return TransferResult.more(response);
        }
        if (payloadIndex == CARD_SECTOR_SIZE) {
            int response = memcardPreviousByte;
            memcardChecksumValid = (value & 0xFF) == (memcardChecksum & 0xFF);
            if (memcardAddressValid && memcardChecksumValid) {
                int base = memcardAddress * CARD_SECTOR_SIZE;
                for (int i = 0; i < CARD_SECTOR_SIZE; i++) {
                    card.writeByte(base + i, memcardWriteBuffer[i] & 0xFF);
                }
                try {
                    card.flush();
                } catch (IOException ex) {
                    Log.error("Failed to persist memory card slot " + (selectedPort + 1), ex);
                }
                IntConsumer listener = memoryCardWriteListener;
                if (listener != null) {
                    try {
                        listener.accept(selectedPort + 1);
                    } catch (RuntimeException ex) {
                        Log.warn("Memory card write listener failed: " + ex.getMessage());
                    }
                }
            }
            commandStep++;
            return TransferResult.more(response);
        }
        if (payloadIndex == CARD_SECTOR_SIZE + 1) {
            commandStep++;
            return TransferResult.more(0x5C);
        }
        if (payloadIndex == CARD_SECTOR_SIZE + 2) {
            commandStep++;
            return TransferResult.more(0x5D);
        }

        int response = !memcardAddressValid ? 0xFF : memcardChecksumValid ? 0x47 : 0x4E;
        if (Log.isDebugEnabled()) {
            Log.debug("Memory card transaction done. port=" + selectedPort
                + " addr=0x" + Integer.toHexString(memcardAddress)
                + " write=true result=0x" + Integer.toHexString(response));
        }
        resetSession();
        return TransferResult.last(response);
    }

    private MemoryCard selectedMemoryCard() {
        return selectedPort == 0 ? slot1 : slot2;
    }

    private ControllerDevice selectedController() {
        if (selectedPort == 0) {
            return controller1Connected ? controllers[0] : null;
        }
        return controller2Connected ? controllers[1] : null;
    }

    private ControllerDevice activeController() {
        if (activeControllerPort == 0) {
            return controller1Connected ? controllers[0] : null;
        }
        if (activeControllerPort == 1) {
            return controller2Connected ? controllers[1] : null;
        }
        return null;
    }

    private DigitalController digitalController(int port) {
        validatePort(port);
        ControllerDevice controller = controllers[port];
        if (controller instanceof DigitalController digital) {
            return digital;
        }
        if (controller instanceof MultitapController multitap
            && multitap.controller(0) instanceof DigitalController digital) {
            return digital;
        }
        return null;
    }

    private void installRumbleHandler(int port) {
        ControllerDevice controller = controllers[port];
        if (controller instanceof DigitalController digital) {
            digital.setRumbleHandler(rumbleHandlers[port]);
        } else if (controller instanceof MultitapController multitap
            && multitap.controller(0) instanceof DigitalController digital) {
            digital.setRumbleHandler(rumbleHandlers[port]);
        }
    }

    private static void validatePort(int port) {
        if (port < 0 || port > 1) {
            throw new IllegalArgumentException("Controller port must be 0 or 1: " + port);
        }
    }

    private void resetSession() {
        if (currentDevice == DeviceType.CONTROLLER) {
            ControllerDevice activeController = activeController();
            if (activeController != null) {
                activeController.cancelTransaction();
            }
        }
        currentDevice = DeviceType.NONE;
        activeControllerPort = -1;
        commandStep = 0;
        memcardCommand = 0;
        memcardAddress = 0;
        memcardChecksum = 0;
        memcardPreviousByte = 0;
        memcardAddressValid = false;
        memcardChecksumValid = false;
    }

    private void hardReset() {
        interruptController.clear(7);
        interruptController.clear(10);
        mode = 0;
        control = 0;
        baudrate = 0;
        baudrateTimer = 0;
        baudrateReload = 0;
        selectedPort = 0;
        irqPending = false;
        ackPulseActive = false;
        ackDelayRemaining = 0;
        ackCyclesRemaining = 0;
        queuedTxData = -1;
        holdingTxData = -1;
        queuedTxEnableLatched = false;
        holdingTxEnableLatched = false;
        serialCyclesRemaining = 0;
        rxFifo.clear();
        lastRxByte = 0;
        emptyRxReads = 0;
        lightgunIrqLineActive = false;
        resetSession();
    }

    private int transferCyclesPerByte() {
        int factor = baudrateFactor();
        int bitCycles = ((baudrate & 0xFFFF) * factor) & ~1;
        bitCycles = Math.max(1, bitCycles);
        // SIO0 peripherals require eight-bit characters.
        return Math.max(1, bitCycles * 8);
    }

    private int baudrateFactor() {
        return switch (mode & 0x03) {
            case 2 -> 16;
            case 3 -> 64;
            default -> 1;
        };
    }

    private void reloadBaudrateTimer() {
        baudrateReload = (((baudrate & 0xFFFF) * baudrateFactor()) & ~1) >>> 1;
        baudrateTimer = baudrateReload;
    }

    private void advanceBaudrateTimer(int cycles) {
        int reload = baudrateReload;
        if (reload == 0) {
            baudrateTimer = 0;
            return;
        }
        if (baudrateTimer <= 0 || baudrateTimer > reload) {
            baudrateTimer = reload;
        }
        if (cycles < baudrateTimer) {
            baudrateTimer -= cycles;
            return;
        }
        int afterReload = (cycles - baudrateTimer) % reload;
        baudrateTimer = afterReload == 0 ? reload : reload - afterReload;
    }

    private void scheduleAck(int extraDelay) {
        int normalDelay = Math.max(100,
            NORMAL_ACK_FROM_TRANSFER_START_CYCLES - transferCyclesPerByte());
        int requestedDelay = normalDelay + Math.max(0, extraDelay);
        if (ackPulseActive) {
            // A correctly driven transaction never overlaps ACK pulses.
            ackDelayRemaining = Math.max(ackDelayRemaining, requestedDelay);
            return;
        }
        ackDelayRemaining = requestedDelay;
    }

    private void beginAckPulse() {
        ackPulseActive = true;
        ackCyclesRemaining = ACK_LOW_CYCLES;
        if ((control & CTRL_DSR_IRQ_ENABLE) != 0) {
            setIrqPending();
        }
    }

    private void clearIrq() {
        irqPending = false;
        interruptController.clear(7);
    }

    private void evaluateLevelInterrupts() {
        if (ackPulseActive && (control & CTRL_DSR_IRQ_ENABLE) != 0) {
            setIrqPending();
        }
        if ((control & CTRL_TX_IRQ_ENABLE) != 0
            && (status() & (STATUS_TX_READY | STATUS_TX_IDLE)) != 0) {
            setIrqPending();
        }
        if ((control & CTRL_RX_IRQ_ENABLE) != 0
            && rxFifo.size() >= rxInterruptThreshold()) {
            setIrqPending();
        }
    }

    private int rxInterruptThreshold() {
        return 1 << ((control >>> 8) & 0x03);
    }

    private void setIrqPending() {
        if (irqPending) {
            return;
        }
        irqPending = true;
        interruptController.raise(7);
    }

    private void pushRxByte(int value) {
        value &= 0xFF;
        if (rxFifo.size() >= RX_FIFO_CAPACITY) {
            rxFifo.removeLast();
        }
        rxFifo.addLast(value);
        lastRxByte = value;
        emptyRxReads = 0;
    }

    private int popRxByte() {
        if (!rxFifo.isEmpty()) {
            int value = rxFifo.removeFirst() & 0xFF;
            lastRxByte = value;
            emptyRxReads = 0;
            evaluateLevelInterrupts();
            return value;
        }
        if (emptyRxReads++ < 2) {
            return lastRxByte & 0xFF;
        }
        return 0;
    }

    private int peekRxByte(int index) {
        if (index < 0) {
            return 0;
        }
        Iterator<Integer> iterator = rxFifo.iterator();
        int current = 0;
        while (iterator.hasNext()) {
            int value = iterator.next() & 0xFF;
            if (current++ == index) {
                return value;
            }
        }
        return rxFifo.isEmpty() ? lastRxByte & 0xFF : rxFifo.peekLast() & 0xFF;
    }

    public State copyState() {
        State state = new State();
        state.rxFifo = rxFifo.stream().mapToInt(Integer::intValue).toArray();
        state.controller1 = controllers[0] == null ? null : controllers[0].copyState();
        state.controller2 = controllers[1] == null ? null : controllers[1].copyState();
        state.controller1Connected = controller1Connected;
        state.controller2Connected = controller2Connected;
        state.currentDevice = currentDevice.ordinal();
        state.activeControllerPort = activeControllerPort;
        state.mode = mode;
        state.control = control;
        state.baudrate = baudrate;
        state.baudrateTimer = baudrateTimer;
        state.commandStep = commandStep;
        state.selectedPort = selectedPort;
        state.memcardCommand = memcardCommand;
        state.memcardAddress = memcardAddress;
        state.memcardChecksum = memcardChecksum;
        state.memcardPreviousByte = memcardPreviousByte;
        state.memcardAddressValid = memcardAddressValid;
        state.memcardChecksumValid = memcardChecksumValid;
        state.memcardWriteBuffer = memcardWriteBuffer.clone();
        state.queuedTxData = queuedTxData;
        state.holdingTxData = holdingTxData;
        state.queuedTxEnableLatched = queuedTxEnableLatched;
        state.holdingTxEnableLatched = holdingTxEnableLatched;
        state.serialCyclesRemaining = serialCyclesRemaining;
        state.ackDelayRemaining = ackDelayRemaining;
        state.ackCyclesRemaining = ackCyclesRemaining;
        state.ackPulseActive = ackPulseActive;
        state.irqPending = irqPending;
        state.lastRxByte = lastRxByte;
        state.emptyRxReads = emptyRxReads;
        state.lightgunIrqLineActive = lightgunIrqLineActive;
        state.slot1Flag = slot1 == null ? 0 : slot1.flag();
        state.slot2Flag = slot2 == null ? 0 : slot2.flag();
        return state;
    }

    public void loadState(State state) {
        if (state == null) {
            return;
        }
        rxFifo.clear();
        if (state.rxFifo != null) {
            for (int value : state.rxFifo) {
                if (rxFifo.size() == RX_FIFO_CAPACITY) {
                    break;
                }
                rxFifo.addLast(value & 0xFF);
            }
        }
        controllers[0] = ControllerDeviceFactory.restore(state.controller1);
        controllers[1] = ControllerDeviceFactory.restore(state.controller2);
        // Old version-1 snapshots had two implicit DualShock devices.
        if (controllers[0] == null) {
            controllers[0] = new DigitalController();
        }
        if (controllers[1] == null) {
            controllers[1] = new DigitalController();
        }
        controller1Connected = state.controller1Connected == null || state.controller1Connected;
        controller2Connected = Boolean.TRUE.equals(state.controller2Connected);
        refreshLightgunSampling();
        installRumbleHandler(0);
        installRumbleHandler(1);
        DeviceType[] values = DeviceType.values();
        currentDevice = state.currentDevice >= 0 && state.currentDevice < values.length
            ? values[state.currentDevice]
            : DeviceType.NONE;
        activeControllerPort = state.activeControllerPort == null
            ? (currentDevice == DeviceType.CONTROLLER ? state.selectedPort : -1)
            : state.activeControllerPort;
        mode = state.mode;
        control = state.control & CTRL_READABLE_MASK;
        baudrate = state.baudrate;
        baudrateReload = (((baudrate & 0xFFFF) * baudrateFactor()) & ~1) >>> 1;
        baudrateTimer = state.baudrateTimer;
        commandStep = state.commandStep;
        selectedPort = state.selectedPort;
        memcardCommand = state.memcardCommand;
        memcardAddress = state.memcardAddress;
        memcardChecksum = state.memcardChecksum;
        memcardPreviousByte = state.memcardPreviousByte;
        memcardAddressValid = state.memcardAddressValid;
        memcardChecksumValid = state.memcardChecksumValid;
        if (state.memcardWriteBuffer != null) {
            System.arraycopy(state.memcardWriteBuffer, 0, memcardWriteBuffer, 0,
                Math.min(state.memcardWriteBuffer.length, memcardWriteBuffer.length));
        }
        queuedTxData = state.queuedTxData;
        holdingTxData = state.holdingTxData;
        queuedTxEnableLatched = state.queuedTxEnableLatched;
        holdingTxEnableLatched = state.holdingTxEnableLatched;
        serialCyclesRemaining = state.serialCyclesRemaining;
        ackDelayRemaining = state.ackDelayRemaining;
        ackCyclesRemaining = state.ackCyclesRemaining;
        ackPulseActive = state.ackPulseActive;
        irqPending = state.irqPending;
        lastRxByte = state.lastRxByte;
        emptyRxReads = state.emptyRxReads;
        lightgunIrqLineActive = state.lightgunIrqLineActive;
        if (slot1 != null) {
            slot1.restoreFlag(state.slot1Flag);
        }
        if (slot2 != null) {
            slot2.restoreFlag(state.slot2Flag);
        }
        if (irqPending) {
            interruptController.raise(7);
        } else {
            interruptController.clear(7);
        }
        if (lightgunIrqLineActive) {
            interruptController.raise(10);
        } else {
            interruptController.clear(10);
        }
    }

    private record TransferResult(int response, boolean acknowledge, int extraAckDelay) {
        private static final TransferResult LAST_FF = last(0xFF);

        private static TransferResult more(int response) {
            return new TransferResult(response & 0xFF, true, 0);
        }

        private static TransferResult moreDelayed(int response, int cycles) {
            return new TransferResult(response & 0xFF, true, Math.max(0, cycles));
        }

        private static TransferResult last(int response) {
            return new TransferResult(response & 0xFF, false, 0);
        }
    }

    public static final class State {
        int[] rxFifo;
        ControllerDeviceState controller1;
        ControllerDeviceState controller2;
        Boolean controller1Connected;
        Boolean controller2Connected;
        int currentDevice;
        Integer activeControllerPort;
        int mode;
        int control;
        int baudrate;
        int baudrateTimer;
        int commandStep;
        int selectedPort;
        int memcardCommand;
        int memcardAddress;
        int memcardChecksum;
        int memcardPreviousByte;
        boolean memcardAddressValid;
        boolean memcardChecksumValid;
        byte[] memcardWriteBuffer;
        int queuedTxData;
        int holdingTxData;
        boolean queuedTxEnableLatched;
        boolean holdingTxEnableLatched;
        int serialCyclesRemaining;
        int ackDelayRemaining;
        int ackCyclesRemaining;
        boolean ackPulseActive;
        boolean irqPending;
        int lastRxByte;
        int emptyRxReads;
        boolean lightgunIrqLineActive;
        int slot1Flag;
        int slot2Flag;
    }
}
